(in-package :flute)

(defparameter *attribute-belongs-to*
  '((accept	input)
    (accept-charset	form)
    (accesskey	*)
    (action	form)
    (alt	area img input)
    (async	script)
    (autocomplete	form input)
    (autofocus	button input select textarea)
    (autoplay	audio video)
    (charset	meta script)
    (checked	input)
    (cite	blockquote del ins q)
    (class	*)
    (cols	textarea)
    (colspan	td th)
    (content	meta)
    (contenteditable	*)
    (controls	audio video)
    (coords	area)
    (data	object)
    (data-*	*) ; This is not actual attr, but still good for eldoc hint purpose
    (datetime	del ins |time|)
    (default	track)
    (defer	script)
    (dir	*)
    (dirname	input textarea)
    (disabled	button fieldset input optgroup option select textarea)
    (download	a area)
    (draggable	*)
    (dropzone	*)
    (enctype	form)
    (for	label output)
    (form	button fieldset input label meter object output select textarea)
    (formaction	button input)
    (headers	td th)
    (height	canvas embed iframe img input object video)
    (hidden	*)
    (high	meter)
    (href	a area base link)
    (hreflang	a area link)
    (http-equiv	meta)
    (id	*)
    (ismap	img)
    (kind	track)
    (label	track option optgroup)
    (lang	*)
    (list	input)
    (loop	audio video)
    (low	meter)
    (max	input meter progress)
    (maxlength	input textarea)
    (media	a area link source style)
    (method	form)
    (min	input meter)
    (multiple	input select)
    (muted	video audio)
    (name	button fieldset form iframe input |map| meta object output param select textarea)
    (novalidate	form)
    (onabort	audio embed img object video)
    (onafterprint	body)
    (onbeforeprint	body)
    (onbeforeunload	body)
    (onblur	+)
    (oncanplay	audio embed object video)
    (oncanplaythrough	audio video)
    (onchange	+)
    (onclick	+)
    (oncontextmenu	+)
    (oncopy	+)
    (oncuechange	track)
    (oncut	+)
    (ondblclick	+)
    (ondrag	+)
    (ondragend	+)
    (ondragenter	+)
    (ondragleave	+)
    (ondragover	+)
    (ondragstart	+)
    (ondrop	+)
    (ondurationchange	audio video)
    (onemptied	audio video)
    (onended	audio video)
    (onerror	audio body embed img object script style video)
    (onfocus	+)
    (onhashchange	body)
    (oninput	+)
    (oninvalid	+)
    (onkeydown	+)
    (onkeypress	+)
    (onkeyup	+)
    (onload	body iframe img input link script style)
    (onloadeddata	audio video)
    (onloadedmetadata	audio video)
    (onloadstart	audio video)
    (onmousedown	+)
    (onmousemove	+)
    (onmouseout	+)
    (onmouseover	+)
    (onmouseup	+)
    (onmousewheel	+)
    (onoffline	body)
    (ononline	body)
    (onpagehide	body)
    (onpageshow	body)
    (onpaste	+)
    (onpause	audio video)
    (onplay	audio video)
    (onplaying	audio video)
    (onpopstate	body)
    (onprogress	audio video)
    (onratechange	audio video)
    (onreset	form)
    (onresize	body)
    (onscroll	+)
    (onsearch	input)
    (onseeked	audio video)
    (onseeking	audio video)
    (onselect	+)
    (onstalled	audio video)
    (onstorage	body)
    (onsubmit	form)
    (onsuspend	audio video)
    (ontimeupdate	audio video)
    (ontoggle	details)
    (onunload	body)
    (onvolumechange	audio video)
    (onwaiting	audio video)
    (onwheel	+)
    (open	details)
    (optimum	meter)
    (pattern	input)
    (placeholder	input textarea)
    (poster	video)
    (preload	audio video)
    (readonly	input textarea)
    (rel	a area link)
    (required	input select textarea)
    (reversed	ol)
    (rows	textarea)
    (rowspan	td th)
    (sandbox	iframe)
    (scope	th)
    (selected	option)
    (shape	area)
    (size	input select)
    (sizes	img link source)
    (span	col colgroup)
    (spellcheck	*)
    (src	audio embed iframe img input script source track video)
    (srcdoc	iframe)
    (srclang	track)
    (srcset	img source)
    (start	ol)
    (step	input)
    (style	*)
    (tabindex	*)
    (target	a area base form)
    (title	*)
    (translate	*)
    (type	button embed input link menu object script source style)
    (usemap	img object)
    (value	button input li option meter progress param)
    (width	canvas embed iframe img input object video)
    (wrap	textarea)))

(defparameter *builtin-elements-list*
  '(a abbr address area article aside audio b base bdi bdo blockquote
    body br button canvas caption cite code col colgroup data datalist
    dd del details dfn dialog div dl dt em embed fieldset figcaption
    figure footer form h1 h2 h3 h4 h5 h6 head header hr i iframe
    img input ins kbd label legend li link main |map| mark meta meter nav
    noscript object ol optgroup option output p param picture pre progress
    q rp rt ruby s samp script section select small source span strong
    style sub summary sup svg table tbody td template textarea tfoot th
    thead |time| title tr track u ul var video wbr))

(defparameter *+-except-elements* '(base bdo br head html iframe meta param script style title))

(defvar *element-attrs* (make-hash-table))

(defvar *element-attrs-calculated* (make-hash-table))

(defvar *builtin-elements* (make-hash-table))

(dolist (element *builtin-elements-list*)
  (setf (gethash (make-keyword element) *builtin-elements*) t))

(dolist (attr *attribute-belongs-to*)
  (dolist (elem (cdr *attribute-belongs-to*))
    (push (car attr) (gethash elem *element-attrs*))))

(loop for element being each hash-key of *builtin-elements*
   do (setf (gethash element *element-attrs-calculated*)
            (sort (append (gethash element *element-attrs*) (gethash '* *element-attrs*)
                          (unless (find element *+-except-elements*)
                            (gethash '+ *element-attrs*)))
                  #'string<)))
